// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Grad_Project.Models
{
    [Table("Card")]
    public partial class Card
    {
        [Key]
        public int id { get; set; }
        public string Userid { get; set; }
        public int? Productid { get; set; }
        public int? Qty { get; set; }

        [ForeignKey("Productid")]
        [InverseProperty("Cards")]
        public virtual Product Product { get; set; }
    }
}