// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Grad_Project.Models
{
    public partial class cart
    {
        public int id { get; set; }
        [ForeignKey("user")]
        public string userID { get; set; }
        public int? productID { get; set; }
        public int Qty { get; set; }
        public decimal? ttlPrice { get; set; }
        public string userName { get; set; }
        public virtual product product { get; set; }
        public virtual AspNetUser user { get; set; }
    }
}