// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Grad_Project.Models
{
    public partial class category
    {
        public category()
        {
            products = new HashSet<product>();
        }

        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string photo { get; set; }

        public virtual ICollection<product> products { get; set; }
    }
}