// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Grad_Project.Models
{
    public partial class payment
    {
        public int id { get; set; }
        public int? userID { get; set; }
        public string creditCard { get; set; }

        public virtual user user { get; set; }
    }
}