// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Grad_Project.Models
{
    public partial class payment
    {
        public int id { get; set; }
        [ForeignKey("user")]
        public string userID { get; set; }
        public string creditCard { get; set; }

        public virtual AspNetUser user { get; set; }
    }
}