// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Grad_Project.Models
{
    [Table("Product")]
    public partial class Product
    {
        public Product()
        {
            Cards = new HashSet<Card>();
        }

        [Key]
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Price { get; set; }
        public int? Catid { get; set; }
        public string Photo { get; set; }

        [ForeignKey("Catid")]
        [InverseProperty("Products")]
        public virtual Category Cat { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<Card> Cards { get; set; }
    }
}