// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Grad_Project.Models
{
    [Table("Review")]
    public partial class Review
    {
        [Key]
        public int id { get; set; }
        public string Name { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        public string subject { get; set; }
        public string Description { get; set; }
    }
}